# ==================================================================================== #
# APPLICATION CONFIGURATION
# ==================================================================================== #
spring:
  application:
    name: ms-pharmacys-turn
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

# ==================================================================================== #
# REST SERVICES
# ==================================================================================== #
# Pharmacy minsal source
# ------------------------------ #
pharmacy:
  farmanet-host: https://farmanet.minsal.cl/
  minsal-host: https://midas.minsal.cl
  seremienlinea-host: https://seremienlinea.minsal.cl
  turns:
    url: ${pharmacy.farmanet-host}/index.php/ws/getLocalesTurnos
  premises:
    url: ${pharmacy.minsal-host}/farmacia_v2/WS/getLocales.php
  seremienlinea:
    url: ${pharmacy.seremienlinea-host}/farmacias/mapa.php

logging:
  level:
    liquibase: INFO


